[project]
name = "tsv-pgai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pgai[sqlalchemy]>=0.9.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy[postgresql]>=2.0.39",
]
